---
name: App CI

permissions:
  id-token: write

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        app: [mu, nu, tu]
    uses: andreswebs/gh-actions/.github/workflows/aws-ecr-push-image.yml@main
    with:
      runs-on: ubuntu-latest
      aws-region: ${{ vars.AWS_REGION }}
      role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
      ecr-repo-name: andreswebs/argo-example/${{ matrix.app }}
      ecr-registry-type: public
      add-image-default-tag: true
      image-default-tag: latest
      image-artifact: image-${{ matrix.app }}
      context-dir: .
      matrix-step-name: build
      matrix-key: ${{ matrix.app }}
      build-args: |
        APP_NAME=${{ matrix.app }}

  release-dev:
    runs-on: ubuntu-latest
    needs: [build]

    strategy:
      matrix:
        app: [mu, nu, tu]

    env:
      CLUSTER_NAME: dev
      APP_NAME: ${{ matrix.app }}
      K8S_CONFIG_REPO: andreswebs/argo-example-k8s-config-alt
      CHART_DIR: ./clusters/dev/${{ matrix.app }}

    steps:
      - name: Upgrade Chart
        uses: andreswebs/gh-actions/.github/actions/helm-chart-upgrade-via-pr@dev
        with:
          token: ${{ secrets.K8S_CONFIG_TOKEN }}
          repository: ${{ env.K8S_CONFIG_REPO }}
          image-artifact: image-${{ env.APP_NAME }}
          chart-dir: ${{ env.CHART_DIR }}
          chart-name: ${{ env.APP_NAME }}
