---
name: App CI

permissions:
  id-token: write

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        app:
          - mu
          # - nu
          # - tu
    uses: andreswebs/gh-actions/.github/workflows/aws-ecr-push-image.yml@main
    with:
      runs-on: ubuntu-latest
      aws-region: ${{ vars.AWS_REGION }}
      role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
      ecr-repo-name: andreswebs/argo-example/${{ matrix.app }}
      ecr-registry-type: public
      add-image-default-tag: true
      image-default-tag: latest
      image-artifact: image-${{ matrix.app }}
      context-dir: .
      build-args: |
        APP_NAME=${{ matrix.app }}

  release-dev:
    needs: [build]

    strategy:
      matrix:
        app:
          - mu
          # - nu
          # - tu

    uses: andreswebs/gh-actions/.github/workflows/app-upgrade.yml@dev
    with:
      runs-on: ubuntu-latest
      aws-region: ${{ vars.AWS_REGION }}
      role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
      image-artifact: image-${{ matrix.app }}
      secret-id: /andreswebs-public-images/github/example-automation
      git-repo: andreswebs-public-images/argo-example-k8s-config
      app-name: ${{ matrix.app }}
      app-dir: apps/${{ matrix.app }}/overlays/dev
      app-file: ${{ matrix.app }}.helm.values.yaml
      auto-merge: true
