---
name: App CI

permissions:
  id-token: write

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        app: [mu, nu, tu]
    uses: andreswebs/gh-actions/.github/workflows/aws-ecr-push-image.yml@main
    with:
      runs-on: ubuntu-latest
      aws-region: ${{ vars.AWS_REGION }}
      role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
      ecr-repo-name: andreswebs/argo-example/${{ matrix.app }}
      ecr-registry-type: public
      add-image-default-tag: true
      image-default-tag: latest
      image-artifact: image-${{ matrix.app }}
      context-dir: .
      matrix-step-name: build
      matrix-key: ${{ matrix.app }}
      build-args: |
        APP_NAME=${{ matrix.app }}

  secret:
    runs-on: ubuntu-latest
    needs: [build]

    outputs:
      gh-app-id: ${{ steps.secret.outputs.gh-app-id }}
      gh-app-prv-key: ${{ steps.secret.outputs.gh-app-prv-key }}

    steps:
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}

      - name: Get Secret
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          parse-json-secrets: true
          secret-ids: |
            ARGOCD,/tmp/ARGOCD_CONFIG

      # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#multiline-strings
      - name: Pass Secret
        id: secret
        run: |
          echo "gh-app-id=${ARGOCD_GITHUB_APP_ID}" >> $GITHUB_OUTPUT

          {
            echo 'gh-app-prv-key<<ENDOFTEXT'
            echo "${ARGOCD_GITHUB_APP_PRIVATE_KEY}" | base64 -d
            echo ENDOFTEXT
          } >> $GITHUB_OUTPUT

  release-dev:
    needs: [build, secret]

    strategy:
      matrix:
        app: [mu, nu, tu]

    uses: andreswebs/gh-actions/.github/workflows/helm-upgrade-chart.yml@dev
    with:
      runs-on: ubuntu-latest
      image-artifact: image-${{ matrix.app }}
      git-repo: andreswebs-public-images/argo-example-k8s-config-alt
      chart-dir: ./clusters/dev/${{ matrix.app }}
      chart-name: ${{ matrix.app }}
      # gh-app-id: ${{ needs.secret.outputs.gh-app-id }}
      # gh-app-prv-key: ${{ needs.secret.outputs.gh-app-prv-key }}
    secrets:
      gh-app-client-id: ${{ needs.secret.outputs.gh-app-id }}
      gh-app-prv-key: ${{ needs.secret.outputs.gh-app-prv-key }}
      # gh-app-client-id: ${{ secrets.GH_APP_CLIENT_ID }}
      # gh-app-prv-key: ${{ secrets.GH_APP_PRV_KEY }}
