---
name: App CI

permissions:
  id-token: write

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        app: [mu, nu, tu]
    uses: andreswebs/gh-actions/.github/workflows/aws-ecr-push-image.yml@main
    with:
      runs-on: ubuntu-latest
      aws-region: ${{ vars.AWS_REGION }}
      role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
      ecr-repo-name: andreswebs/argo-example/${{ matrix.app }}
      ecr-registry-type: public
      add-image-default-tag: true
      image-default-tag: latest
      context-dir: .
      matrix-step-name: build
      matrix-key: ${{ matrix.app }}
      build-args: |
        APP_NAME=${{ matrix.app }}

  release-dev:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     app: [mu, nu, tu]

    env:
      CLUSTER_NAME: dev
      K8S_CONFIG_REPO: andreswebs/argo-example-k8s-config-alt

    steps:
      ## TODO: checkout the target repo
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ env.K8S_CONFIG_REPO }}
          ref: main
          token: ${{ secrets.K8S_CONFIG_TOKEN }}

      - name: Inspect
        run: |
          pwd
          ls -lia
          which yq
